/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const parseEmail: (a: number, b: number) => number;
export const generateAccountCode: () => number;
export const generateAccountSalt: (a: number, b: number, c: number, d: number) => number;
export const padEmailAddr: (a: number, b: number) => number;
export const generateCircuitInputsWithDecomposedRegexesAndExternalInputs: (a: number, b: number, c: number, d: number, e: number) => number;
export const sha256Pad: (a: number, b: number) => number;
export const publicKeyHash: (a: number) => number;
export const generateEmailCircuitInput: (a: number, b: number, c: number, d: number, e: number) => number;
export const extractRandFromSignature: (a: number, b: number) => number;
export const emailAddrCommitWithSignature: (a: number, b: number, c: number, d: number) => number;
export const bytesToFields: (a: number) => number;
export const emailNullifier: (a: number, b: number) => number;
export const extractInvitationCodeIdxes: (a: number, b: number, c: number) => void;
export const extractInvitationCodeWithPrefixIdxes: (a: number, b: number, c: number) => void;
export const padString: (a: number, b: number, c: number) => number;
export const extractSubstrIdxes: (a: number, b: number, c: number, d: number, e: number) => void;
export const extractSubstr: (a: number, b: number, c: number, d: number, e: number) => void;
export const extractEmailAddrIdxes: (a: number, b: number, c: number) => void;
export const extractEmailDomainIdxes: (a: number, b: number, c: number) => void;
export const extractFromAllIdxes: (a: number, b: number, c: number) => void;
export const extractFromAddrIdxes: (a: number, b: number, c: number) => void;
export const extractToAllIdxes: (a: number, b: number, c: number) => void;
export const extractToAddrIdxes: (a: number, b: number, c: number) => void;
export const extractSubjectAllIdxes: (a: number, b: number, c: number) => void;
export const extractBodyHashIdxes: (a: number, b: number, c: number) => void;
export const extractTimestampIdxes: (a: number, b: number, c: number) => void;
export const extractMessageIdIdxes: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc5467d1c6d6d3cd1: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures__invoke2_mut__hd521fbd72b14027e: (a: number, b: number, c: number, d: number) => void;
