name: Publish

on:
  push:
    branches: ["main"]

permissions: write-all

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-release
      - name: Publish binaries
        run: npm run upload-binary
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
